### ISSUE TITLE
ReferenceError: data is not defined

### ISSUE THREAD

**Issue by hmndss** [lucid-eleven/nft-discord-bot#1]
Hi! I'm trying to add this bot to my Discord but the Heroku logs shows this error. Any clue how to fix this?

```

2021-09-30T22:39:38.019199+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
2021-09-30T22:39:38.019206+00:00 app[web.1]:     at Object.execute (/app/cronjobs/sales.js:75:17)
2021-09-30T22:39:38.019207+00:00 app[web.1]:     at runMicrotasks (<anonymous>)
2021-09-30T22:39:38.019207+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-09-30T22:39:38.019241+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

**Comment by lucid-eleven** [comment]
This is weird, I haven't looked at this code for a while, now I'm wondering how it ever worked.. I just pushed a change up, hopefully fixes it.
