### ISSUE TITLE
[Symbol(code)]: 'TOKEN_INVALID'

### ISSUE THREAD

**Issue by samershakk** [lucid-eleven/nft-discord-bot#8]
everytime i try to run it, says [Symbol(code)]: 'TOKEN_INVALID', even though i am sure and have tested different working bot tokens :(

**Comment by lucid-eleven** [comment]
I'd guess most likely you didn't copy/paste your bot token correctly, but hard to confirm without more details.

**Comment by Erzos91** [comment]
Yes same problem for me, I reset the token but the problem still 

PS C:\Users\ipou\Downloads\nft-discord-bot> npm start

> nft-discord-bot@1.0.0 start
> node bot.js

Discord Bot app listening at http://localhost:5000
C:\Users\ipou\Downloads\nft-discord-bot\node_modules\discord.js\src\client\Client.js:206
    if (!token || typeof token !== 'string') throw new Error('TOKEN_INVALID');
                                                   ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\ipou\Downloads\nft-discord-bot\node_modules\discord.js\src\client\Client.js:206:52)
    at Object.<anonymous> (C:\Users\ipou\Downloads\nft-discord-bot\bot.js:62:8)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)   
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'TOKEN_INVALID'
}
